Movie module - Show RomHash Region, if not null
TASVideos/tasvideos pull request #1090
Opened 2022-02-09 02:04 UTC by adelikat

Conditionally shows the region, if the rom hash entry is added
The value needs to not be in the title so that it can be styled independently, so I put it all the way to the left.  I also only show it if it is relevant, which currently are these values:
J => (JPN),
E => (Europe),
EU => (USA/Europe)

We can easily configure these values if want different examples.

![image](https://user-images.githubusercontent.com/1679846/153107570-d54a0550-c65e-4212-853b-33ef3f0c9572.png)

![image](https://user-images.githubusercontent.com/1679846/153107880-db964797-2379-4efc-afbb-e0c7608c8e3d.png)

2022-02-09 06:18 UTC, meshuggahtas commented
I think (U) USA should be added too

2022-02-09 14:20 UTC, vadosnaprimer commented
I think `JPN` should be turned into `Japan`. Alpha-3 codes are used for countries, but we also have `Europe` and `Asia` which don't have official alpha-3 codes. So instead of inventing codes for those, I think it would be neater to spell out Japan instead.

Also IMO there should be `World` and it should be default and hidden, just like `any` was on the old site. Finally, there should probably also be `unknown`.

Need opinions from @fsvgm777 and @ThunderAxe31

2022-02-09 14:21 UTC, adelikat commented
I dont' know what you mean about hidden.  The RomHash table has all those things, we are just deciding which to show, and what display value to show.

So it sounds like the only change you want is JPN to Japan?

2022-02-09 14:25 UTC, vadosnaprimer commented
Hidden I mean not displayed in publication titles.

Also in the case of [VVVVVV](https://tasvideos.org/Forum/Posts/511442) and possibly other PC games, we need to display numeric game version instead of the region, since region is kinda pointless on PC.

2022-02-10 02:19 UTC, adelikat commented
![image](https://user-images.githubusercontent.com/1679846/153324639-75db7978-44e4-4521-a8e8-1cfbfa59252d.png)

2022-02-10 16:14 UTC, Masterjun3 requested changes

2022-02-10 16:26 UTC, vadosnaprimer commented
For cases when the same game works in all regions, we need to have `World`. `USA/Europe` doesn't include Japan and PAL Asia. PAL Asia games are rare, but if somebody submits a NES game made there and it uses Dendy mode, that's when we used the `Asia` region, to indicate it's running in hybrid mode. This is not critical tho.

On the matter of display, I think it's ok to put region and version within the same pair of parentheses.

2022-02-10 17:04 UTC, ThunderAxe31 commented
I agree that `JPN` should be `Japan`, and that `any` should be `World`.

I don't like the style of `(Japan) (v1.4)`, as in my opinion it makes it unclear that both things are referring to the game version. I suggest instead using `(Japan v1.4)`.

Also, I want to note that there are more combo cases, like Pokémon Mystery Dungeon, in for which a version is known as `USA/Australia`.

2022-02-10 17:06 UTC, adelikat commented
JPN has been changed to Japan already.
and neither any nor world show.

2022-02-10 17:21 UTC, fsvgm777 commented
Okay, kinda late to the party, but I agree with hiding any/World, especially for PC games (DOS, Windows, Linux), where region doesn't really matter.

> Also, I want to note that there are more combo cases, like Pokémon Mystery Dungeon, in for which a version is known as USA/Australia.

I think that can be put as Other or just USA (if GBA)? Same deal with games released exclusively in Germany (Hugo 2 1/2) or France (no movie examples, but I know of some (e.g. Les Visiteurs)).

> I don't like the style of (Japan) (v1.4), as in my opinion it makes it unclear that both things are referring to the game version. I suggest instead using (Japan v1.4).

Agreed.

2022-02-10 17:41 UTC, adelikat commented
![image](https://user-images.githubusercontent.com/1679846/153465060-6fa43915-3d2a-4c93-bc99-7f02228f91b0.png)

2022-02-10 18:04 UTC, vadosnaprimer approved these changes

2022-02-10 20:31 UTC, merged