Make titles bigger on certain pages
TASVideos/tasvideos pull request #1443
Opened 2022-10-19 02:08 UTC by mellonite

Fixes #1087

Title is now larger than Status on Submission Page
![image](https://user-images.githubusercontent.com/26491971/196580500-98538ad6-4147-4418-bb1d-84bbcae8d410.png)

This fix addresses other pages that use header cards as well.

2022-10-21 08:30 UTC, Masterjun3 requested changes
This changes all card sizes. This is not what I wanted with the issue.
Even worse, with this change the titles size are inconsistent. The Games List page is now bigger than the Movies page for example.
The submission threads I mentioned in the issue aren't even changed, so this doesn't even fix the issue at all.

2022-10-25 20:21 UTC, mellonite commented
My apologies, I'm still new to the site, and it seems I didn't understand what you meant by submission threads.

You're right, the use of h1 cards is inconsistent between pages. This is not the ideal implementation for this site.

How do I get to a submission thread from the local development version of the site?

2022-10-25 20:25 UTC, adelikat commented
You can simply create a submission, and the thread will get created.  You just need a parsable movie file

2022-11-12 18:26 UTC, adelikat commented
Rejecting this PR as it takes the wrong approach to the problem as mentioned above

2022-11-12 18:26 UTC, closed without merging

2022-11-12 18:28 UTC, TiKevin83 commented
> You can simply create a submission, and the thread will get created. You just need a parsable movie file

for reference I tend to just download a recent submission's movie file to test this locally, it's pretty straightforward and you don't need to learn how to spin up bizhawk to create one