Add go-back links to 404 page (`/Wiki/PageDoesNotExist`)
TASVideos/tasvideos pull request #1544
Opened 2023-04-11 21:47 UTC by YoshiRulz

...and change wording.

2023-04-11 23:46 UTC, adelikat commented
From a technical perspective, I approve.  I'll defer on whether the specific wording an feature is desired

2023-04-12 16:24 UTC, Masterjun3 commented
I don't understand this PR, what point is there in providing a link to a page that will redirect you back to the page you're on?
And I'm also not sure about the wording of "going back 1 or 2 steps". What are steps? Wouldn't just "page" be a lot more explanatory?

2023-04-12 16:49 UTC, YoshiRulz commented
> I don't understand this PR, what point is there in providing a link to a page that will redirect you back to the page you're on?

To copy-paste and fix a typo. If I'm the only one who would ever use it, you can revert that part.

> And I'm also not sure about the wording of "going back 1 or 2 steps". What are steps? Wouldn't just "page" be a lot more explanatory?

Feel free to change the wording too. There's a baseline of confusion where redirects are involved.

2023-04-12 16:52 UTC, YoshiRulz commented on TASVideos/Pages/Wiki/PageDoesNotExist.cshtml
> +<p><a asp-page="/Wiki/Referrers" asp-route-path="@url">Click here</a> to find referrers in this wiki, <a href="javascript:history.back()">here</a> to go back 2 steps to the referrer, or <a href="/@ur
The one you came from, the `Referer` req. header. Again, replace it with a better wording if you can think of one.

2023-04-12 16:54 UTC, vadosnaprimer commented on TASVideos/Pages/Wiki/PageDoesNotExist.cshtml
> +<p><a asp-page="/Wiki/Referrers" asp-route-path="@url">Click here</a> to find referrers in this wiki, <a href="javascript:history.back()">here</a> to go back 2 steps to the referrer, or <a href="/@ur
"to go back to the page you arrived from"? I could reword it if I knew what it was meant to say exactly.

2023-04-13 10:57 UTC, Masterjun3 commented
Now that I understand what was wanted here, I have a suggestion for a new design.
Instead of going "back 1 or 2 steps" and putting it below everything, my suggestion straight up shows the url, and just says "go back". After all, there is no need to tell people to click a link that will just redirect you back to where you are.

[Image of currently live version](https://user-images.githubusercontent.com/22375320/231736267-aaac6d37-b001-4c64-af66-19e5c7bd1124.png)

[Image of this Pull Request](https://user-images.githubusercontent.com/22375320/231736279-c9e81936-91fc-46f8-9a90-8d02ee119d6b.png)

My suggestion:
![mine](https://user-images.githubusercontent.com/22375320/231736289-0980235e-b82d-42a2-b85a-bcc4c8672ea4.png)

<details><summary>Here is the file:</summary>

```cshtml
@page
@{
	ViewData.SetTitle("DoesNotExist");
	var url = PageContext.HttpContext.Request.Query["url"].ToString().Trim('/');
	bool canEdit = WikiHelper.UserCanEditWikiPage(url, User.Name(), User.Permissions());
	HttpContext.Response.StatusCode = 404;
}
<h2>The page you were looking for does not yet exist.</h2>
<p>The page ( <a href="/@url">@($"{HttpContext.Request.ToBaseUrl()}/{url}")</a> ) does not exist. <a href="javascript:history.back()">Click here</a> to go back.</p>
<p>You can also <a asp-page="/Search/Index" asp-route-searchTerms="@url">search</a> for alternative titles or spellings.</p>
<hr />
Want to create the page?
<br />
<ul>
	@if (!User.IsLoggedIn())
	{
		<li>
			If you are an editor or have rights to edit this page,
			<a asp-page="/Account/Login" asp-route-returnUrl="@HttpContext.CurrentPathToReturnUrl()">log in</a>
			to edit the page.
		</li>
	}
	else if (!canEdit)
	{
		<li>You do not currently have permissions to create this page. If you are not an editor, become an <a asp-page="/Roles/Index" asp-route-role="Editor">editor!</a></li>
	}

	@if (User.IsLoggedIn() && canEdit)
	{
		<li>
			Click here to
			<a asp-page="/Wiki/Edit" asp-route-path="@url">
				edit this page
			</a>
		</li>
		<li>Write the page content, and click Save to create the page.</li>
	}
</ul>

<p>When creating new pages, always ensure that there is some other page that links to the newly created page. Otherwise your page will just become a <a href="/WikiOrphans">wiki orphan</a> that will be quickly forgotten.</p>
<p><a asp-page="/Wiki/Referrers" asp-route-path="@url">Click here</a> to see Referrers to this page.</p>

```

</details>

2023-04-13 10:59 UTC, Masterjun3 requested changes
@YoshiRulz should first reject, adjust, or agree to my suggestion before we merge this.

2023-04-13 17:20 UTC, vadosnaprimer commented
I like the suggestion as a regular user.

2023-04-14 08:05 UTC, Masterjun3 approved these changes

2023-04-14 12:54 UTC, merged