Add fm2 binary parser
TASVideos/tasvideos pull request #1890
Opened 2024-06-27 02:37 UTC by Randomno

FM2 format officially supports binary format, even though the only way you would probably end up with such a movie is by renaming an FM3.

Does this need a test?

2024-06-27 06:48 UTC, Masterjun3 commented
> Does this need a test?

Yes.

2024-06-27 13:36 UTC, adelikat requested changes
Add unit tests please

2024-06-28 06:58 UTC, Randomno commented
Added

2024-06-28 13:36 UTC, adelikat approved these changes

2024-06-28 13:37 UTC, merged